### ISSUE TITLE
Create a new componente for make a scrolling horizontal

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#101]
Example: https://css-tricks.com/pure-css-horizontal-scrolling/
This feature has to be compatible with webview of Android> = 4 and iOS

**Comment by Yash-Handa** [comment]
Hi @fabiorogeriosj 
I would love to contribute to **MobileUI** by adding **horizontal-scroll** component to it.
Please let me know if someone else is working on it or not, So that I can Start with it

**Comment by fabiorogeriosj** [comment]
Hi @Yash-Handa, so far no one is working on this task.

Take time to stay in it ;)

**Comment by Yash-Handa** [comment]
@fabiorogeriosj,
do you want the component to work like the one shown in this post:-  https://css-tricks.com/pure-css-horizontal-scrolling/
because there are some problems with this Trick as stated by the author:- 

## Mobile
I was kind of surprised to find that Android actually understood that the container had been rotated, and let you scroll sideways by swiping left and right.

**iOS, on the other hand, did not play nice.** It acted like the container did not get rotated, so you have to swipe up and down to scroll sideways, which of course is counterintuitive. Also, swiping left and right moves the items up and down in their wrapper, which is unexpected and weird. Setting the overflow to hidden does not alleviate this issue.

**Comment by fabiorogeriosj** [comment]
@Yash-Handa yes,  this needs to work as an example, but needs on Android and iOS.
You need to use other CSS code to work well.
So that's the mission :)

**Comment by galloj** [comment]
@fabiorogeriosj This issue can be closed #103
